# Generated by Django 2.2 on 2019-05-03 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CouponItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=50, null=True)),
                ('promo_code', models.CharField(max_length=100, null=True)),
                ('last_verified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('expired', 'Expired')], max_length=10)),
                ('crawlsite', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CrawlSite')),
                ('retailer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Retailer')),
            ],
            options={
                'verbose_name': 'scrapped Coupon',
            },
        ),
    ]
