# Generated by Django 2.2 on 2019-05-08 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CouponSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('link', models.CharField(max_length=50, null=True)),
                ('page_link', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, null=True)),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('started', 'started'), ('pending', 'pending'), ('running', 'running'), ('finished', 'finished')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
                ('slug_id', models.CharField(max_length=50, null=True)),
                ('link', models.CharField(max_length=50, null=True)),
                ('coupon_sites', models.ManyToManyField(to='main.CouponSite')),
            ],
        ),
        migrations.CreateModel(
            name='CouponItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('promo_code', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('last_verified_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('unverified', 'unverified'), ('valid', 'valid'), ('invalid', 'invalid'), ('expired', 'expired')], default='unverified', max_length=10)),
                ('coupon_from', models.CharField(max_length=50, null=True)),
                ('retailer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Retailer')),
            ],
            options={
                'verbose_name': 'scrapped coupon',
            },
        ),
    ]
