# Generated by Django 2.2.1 on 2019-05-03 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='couponitem',
            name='task_id',
        ),
        migrations.AddField(
            model_name='couponitem',
            name='unique_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crawlsite',
            name='path',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
