# Generated by Django 2.2 on 2019-05-08 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponitem',
            name='expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
