# Generated by Django 2.2 on 2019-05-01 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlSite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='couponitem',
            options={'verbose_name': 'scrapped Coupon'},
        ),
        migrations.AddField(
            model_name='couponitem',
            name='crawlsite',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.CrawlSite'),
        ),
    ]
