# Generated by Django 2.2 on 2019-05-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponitem',
            name='last_verified_date',
            field=models.DateTimeField(null=True),
        ),
    ]
