# Generated by Django 2.2 on 2019-05-06 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190506_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='retailer',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
