# Generated by Django 2.2 on 2019-05-07 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_retailer_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=100, null=True)),
                ('unique_id', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(choices=[('STARTED', 'started'), ('PROGRESS', 'in progress'), ('FINISHED', 'finished')], max_length=10)),
            ],
        ),
    ]
